DROP DATABASE IF EXISTS APP;
CREATE DATABASE APP CHARACTER SET utf8 COLLATE utf8_general_ci;

use APP;

CREATE TABLE USER_BASIC_INFO(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    DOCUMENT_NUMBER VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    TRUSTED_MAIL TINYINT(1) DEFAULT 0,
    CONSTRAINT USER_BASIC_INFO_PK PRIMARY KEY(ID)
);

CREATE TABLE USER(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(100) UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    ENABLED TINYINT(1) DEFAULT 1,
    ID_USER_BASIC_INFO BIGINT NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY(ID),
    CONSTRAINT USER_FK1 FOREIGN KEY(ID_USER_BASIC_INFO) REFERENCES USER_BASIC_INFO(ID)
);

CREATE TABLE ROLE(
    NAME VARCHAR(100) NOT NULL,
    CONSTRAINT ROLE_PK PRIMARY KEY(NAME)
);

CREATE TABLE USER_ROLES(
    ID_USER BIGINT NOT NULL,
    ID_ROLE VARCHAR(100) NOT NULL,
    CONSTRAINT USER_ROLE_PK PRIMARY KEY (ID_USER, ID_ROLE),
    CONSTRAINT USER_ROLE_FK1 FOREIGN KEY(ID_USER) REFERENCES USER(ID),
    CONSTRAINT USER_ROLE_FK2 FOREIGN KEY(ID_ROLE) REFERENCES ROLE(NAME)
);


