INSERT INTO ROLE VALUES("USER");
INSERT INTO ROLE VALUES("ADMIN");
INSERT INTO ROLE VALUES("OTHER_ROLE");

INSERT INTO USER_BASIC_INFO VALUES(DEFAULT, "Juan", "Perez", "37656878", "juanperez@gmail.com",  0 );
INSERT INTO USER_BASIC_INFO VALUES(DEFAULT, "Ludmila", "Gutierrez", "27657778", "ludmi.guti@gmail.com",  0 );


INSERT INTO USER VALUES(DEFAULT, "juan", "$2a$10$XTWNu1/6hzT6aZKTWGxlAOOiKBz5MRTPHhCH3qaUA2Z/DWODkzSty", 1, 1 ); -- pw= juan
INSERT INTO USER VALUES(DEFAULT, "ludmila", "$2a$10$d3ILVMXP9EG3JPtBnpHsOeULbhOZHunEUMtSIz/jjERS3H8gwJSRm", 1, 2 ); -- pw= ludmila

INSERT INTO USER_ROLES VALUES(1,"USER");
INSERT INTO USER_ROLES VALUES(2,"ADMIN");
INSERT INTO USER_ROLES VALUES(2,"USER");